# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20170906_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 14, 26, 53, 998031, tzinfo=utc)),
        ),
    ]
